# Generated by Django 5.2 on 2025-08-14 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pressroom', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reporteradmin',
            name='district',
        ),
        migrations.RemoveField(
            model_name='reporteradmin',
            name='user',
        ),
        migrations.CreateModel(
            name='news',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='news_images/')),
                ('video', models.FileField(blank=True, null=True, upload_to='news_videos/')),
                ('content', models.TextField()),
                ('mandal', models.CharField(max_length=100)),
                ('breaking_news', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('District', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news_items', to='pressroom.district')),
                ('reporter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='news_items', to='pressroom.reporter')),
            ],
        ),
        migrations.DeleteModel(
            name='EditorAdmin',
        ),
        migrations.DeleteModel(
            name='ReporterAdmin',
        ),
    ]
