# Generated by Django 5.2 on 2025-08-08 08:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pressroom', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='user',
        ),
        migrations.RemoveField(
            model_name='reporter',
            name='idproofe',
        ),
        migrations.AddField(
            model_name='reporter',
            name='idproof',
            field=models.FileField(default=1, upload_to='reporters/idproofs/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reporter',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reporter',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='address',
            name='address_line_2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='is_default',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='phone_number',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='address',
            name='postal_code',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='address',
            name='reporter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pressroom.reporter'),
        ),
        migrations.AlterField(
            model_name='reporter',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='reporter',
            name='phone',
            field=models.CharField(default=2, max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reporter',
            name='profile_picture',
            field=models.ImageField(default=1, upload_to='reporters/profile_pictures/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reporter',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
