# Generated by Django 5.2 on 2025-08-08 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pressroom', '0002_remove_address_user_remove_reporter_idproofe_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='address_line_1',
        ),
        migrations.RemoveField(
            model_name='address',
            name='address_line_2',
        ),
        migrations.AddField(
            model_name='address',
            name='district',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='mandal',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
