# Generated by Django 5.2 on 2025-08-15 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pressroom', '0003_rename_phone_number_address_phone_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='phone',
            new_name='phone_number',
        ),
        migrations.RenameField(
            model_name='clusteradmin',
            old_name='profile_picture',
            new_name='passport_photo',
        ),
        migrations.RenameField(
            model_name='clusteradmin',
            old_name='phone',
            new_name='primary_mobile',
        ),
    ]
