# Generated by Django 5.2 on 2025-08-15 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pressroom', '0004_rename_phone_address_phone_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='phone_number',
            new_name='phone',
        ),
        migrations.RenameField(
            model_name='clusteradmin',
            old_name='primary_mobile',
            new_name='phone',
        ),
        migrations.RenameField(
            model_name='clusteradmin',
            old_name='passport_photo',
            new_name='profile_picture',
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
