# Generated by Django 5.2 on 2025-08-15 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pressroom', '0006_rename_district_news_district_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='district',
            new_name='District',
        ),
        migrations.AddField(
            model_name='clusteradmin',
            name='id_proof',
            field=models.FileField(blank=True, null=True, upload_to='id_proofs/'),
        ),
        migrations.AddField(
            model_name='clusteradmin',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='clusteradmin',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='passport_photos/'),
        ),
        migrations.AddField(
            model_name='reporter',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reporter',
            name='idproof',
            field=models.FileField(default=1, upload_to='reporters/idproofs/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reporter',
            name='profile_picture',
            field=models.ImageField(default=1, upload_to='reporters/profile_pictures/'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
